version: '3'
services:
  flask:
    build: pythonChartService
    container_name: backend-flask
    environment:
      - PYTHON UNBUFFERED=True
    restart: on-failure
    ports:
      - 5000:5000
    command: python image_controller.py